apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-job
spec:
  template:
    spec:
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - "--dockerfile=clamscan/clamsacan-lambda-src/Dockerfile"
            - "--context=git://github.com/venkatesh-devops/kaniko.git"
            - "--destination=https://hub.docker.com/r/devopsvenkateshhyd/kaniko:1.0.0"
            - "--oci-layout-path=/kaniko/oci"
          volumeMounts:
            - name: kaniko-secret
              mountPath: /kaniko/.docker/
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: kaniko-secret
          secret:
            secretName: ecr-secret
