apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-job
spec:
  template:
    spec:
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - "--dockerfile=Dockerfile"
            - "--context=dir://path/to/context"
            - "--destination=<YOUR_ECR_URI>:<TAG>"
            - "--oci-layout-path=/kaniko/oci"
          volumeMounts:
            - name: kaniko-secret
              mountPath: /kaniko/.docker/
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: kaniko-secret
          secret:
            secretName: ecr-secret
